# Generated by Django 4.2.7 on 2024-05-19 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user_goals_user_matches_user_red_cards_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='description',
            field=models.TextField(default='Brak opisu'),
        ),
        migrations.AlterField(
            model_name='training',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='training',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
