# Generated by Django 4.2.7 on 2024-05-19 03:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_training_description_alter_training_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='players',
            field=models.ManyToManyField(related_name='trainings', to=settings.AUTH_USER_MODEL),
        ),
    ]
