# Generated by Django 4.2.7 on 2024-05-19 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_training_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='team',
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='api.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='description',
            field=models.TextField(default='Brak opisu'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='api.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
